In [13]:
import polars as pl

lf = pl.LazyFrame(
    {
        "ticker_symbol": [1, 2, 3, 4, 5, 6],
        "b": [
            "2023-01-01",
            "2023-01-02",
            "2024-01-03",
            "2024-01-04",
            "2025-01-05",
            "2025-01-06",
        ],
        " c": [10, 20, 30, 40, 50, 60],
    },
    schema={"ticker_symbol": pl.Int64, "b": pl.String, " c": pl.Int64},
)
df = (
    lf.with_columns(pl.col("b").str.strptime(pl.Date, format="%Y-%m-%d"))
    .with_columns(
        pl.col("b").dt.year().rank("dense").alias("time_index"),
    )
    .collect()
)
df

shape: (6, 4)
┌───────────────┬────────────┬─────┬────────────┐
│ ticker_symbol ┆ b          ┆  c  ┆ time_index │
│ ---           ┆ ---        ┆ --- ┆ ---        │
│ i64           ┆ date       ┆ i64 ┆ u32        │
╞═══════════════╪════════════╪═════╪════════════╡
│ 1             ┆ 2023-01-01 ┆ 10  ┆ 1          │
│ 2             ┆ 2023-01-02 ┆ 20  ┆ 1          │
│ 3             ┆ 2024-01-03 ┆ 30  ┆ 2          │
│ 4             ┆ 2024-01-04 ┆ 40  ┆ 2          │
│ 5             ┆ 2025-01-05 ┆ 50  ┆ 3          │
│ 6             ┆ 2025-01-06 ┆ 60  ┆ 3          │
└───────────────┴────────────┴─────┴────────────┘

In [1]:
import numpy as np
import timeit

# 显示配置信息
# np.show_config()

# 检查链接的库
# print(np.__config__.show())

# 性能测试

# 矩阵乘法测试
size = int(1e4)
a = np.random.rand(size, size)
b = np.random.rand(size, size)

time = timeit.timeit(lambda: a @ b, number=5)
print(f"矩阵乘法时间: {time / 5:.3f} 秒")

矩阵乘法时间: 0.933 秒

In [8]:
import polars as pl

lf = pl.scan_ipc("/mnt/raid0/nfs_from6_readonly/data_frames/stk_market_value.feather")
lf.rename({"__index_level_0__": "date"}).with_columns(
    pl.col("date").str.to_date("%Y%m%d")
).collect()

shape: (2_654, 5_406)
┌───────────┬───────────┬──────────┬──────────┬───┬───────────┬───────────┬───────────┬────────────┐
│ 000001    ┆ 000002    ┆ 000004   ┆ 000005   ┆ … ┆ 688819    ┆ 688981    ┆ 689009    ┆ date       │
│ ---       ┆ ---       ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---        │
│ f64       ┆ f64       ┆ f64      ┆ f64      ┆   ┆ f64       ┆ f64       ┆ f64       ┆ date       │
╞═══════════╪═══════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪════════════╡
│ 1.8303e11 ┆ 1.6457e11 ┆ 1.3176e9 ┆ 3.7488e9 ┆ … ┆ null      ┆ null      ┆ null      ┆ 2015-01-05 │
│ 1.8028e11 ┆ 1.5850e11 ┆ 1.3823e9 ┆ 3.7488e9 ┆ … ┆ null      ┆ null      ┆ null      ┆ 2015-01-06 │
│ 1.7686e11 ┆ 1.5706e11 ┆ 1.3781e9 ┆ 3.7488e9 ┆ … ┆ null      ┆ null      ┆ null      ┆ 2015-01-07 │
│ 1.7092e11 ┆ 1.5000e11 ┆ 1.4209e9 ┆ 3.7488e9 ┆ … ┆ null      ┆ null      ┆ null      ┆ 2015-01-08 │
│ 1.7229e11 ┆ 1.4845e11 ┆ 1.3797e9 ┆ 3.7488e9 ┆ … ┆ null      ┆ null      ┆ null      ┆ 2015-01-09 │
│ …         ┆ …         ┆ …        ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …          │
│ 2.2724e11 ┆ 6.5261e10 ┆ 1.4840e9 ┆ null     ┆ … ┆ 3.0874e10 ┆ 9.0170e11 ┆ 4.0422e10 ┆ 2025-11-27 │
│ 2.2530e11 ┆ 6.4187e10 ┆ 1.5581e9 ┆ null     ┆ … ┆ 3.1214e10 ┆ 9.0882e11 ┆ 4.0838e10 ┆ 2025-11-28 │
│ 2.2686e11 ┆ 6.2040e10 ┆ 1.6362e9 ┆ null     ┆ … ┆ 3.1554e10 ┆ 9.1522e11 ┆ 4.2274e10 ┆ 2025-12-01 │
│ 2.2588e11 ┆ 6.2040e10 ┆ 1.5872e9 ┆ null     ┆ … ┆ 3.1175e10 ┆ 9.0403e11 ┆ 4.2769e10 ┆ 2025-12-02 │
│ 2.2414e11 ┆ 5.9773e10 ┆ 1.5436e9 ┆ null     ┆ … ┆ 3.1204e10 ┆ 8.9299e11 ┆ 4.2374e10 ┆ 2025-12-03 │
└───────────┴───────────┴──────────┴──────────┴───┴───────────┴───────────┴───────────┴────────────┘

In [2]:
import polars as pl

lf = pl.scan_ipc("/mnt/raid0/user_data/DailyFactors/barra/20251127.feather")
df = lf.collect()
df

shape: (5_407, 41)
┌────────┬──────────┬─────────┬────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ sec_id ┆ HBETA    ┆ BTOP    ┆ DTOP   ┆ … ┆ ROA      ┆ DASTD    ┆ CMRA     ┆ HSIGMA   │
│ ---    ┆ ---      ┆ ---     ┆ ---    ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str    ┆ f64      ┆ f64     ┆ f64    ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞════════╪══════════╪═════════╪════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 300916 ┆ 1.780826 ┆ 3.663   ┆ 1.0983 ┆ … ┆ 6.4831   ┆ 0.024465 ┆ 0.524086 ┆ 0.024017 │
│ 688677 ┆ 1.022343 ┆ 4.1331  ┆ 1.2371 ┆ … ┆ 11.1512  ┆ 0.022244 ┆ 0.477089 ┆ 0.022406 │
│ 601033 ┆ 0.385129 ┆ 1.2962  ┆ 3.6166 ┆ … ┆ 3.7534   ┆ 0.014859 ┆ 0.223192 ┆ 0.012524 │
│ 601698 ┆ 1.438294 ┆ 5.4253  ┆ 0.1489 ┆ … ┆ 1.5215   ┆ 0.018872 ┆ 0.28742  ┆ 0.018716 │
│ 300233 ┆ 1.279971 ┆ 1.7857  ┆ 2.2857 ┆ … ┆ 1.4746   ┆ 0.025957 ┆ 0.532852 ┆ 0.028498 │
│ …      ┆ …        ┆ …       ┆ …      ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ 301080 ┆ 1.431957 ┆ 3.7286  ┆ 0.9043 ┆ … ┆ 5.9101   ┆ 0.030293 ┆ 0.707149 ┆ 0.030596 │
│ 300736 ┆ 1.495541 ┆ 32.1308 ┆ 0.0    ┆ … ┆ -14.0227 ┆ 0.031411 ┆ 0.535402 ┆ 0.030158 │
│ 003000 ┆ 0.61597  ┆ 3.8981  ┆ 3.3445 ┆ … ┆ 11.4182  ┆ 0.015178 ┆ 0.227299 ┆ 0.016125 │
│ 603933 ┆ 1.259936 ┆ 3.2915  ┆ 0.3984 ┆ … ┆ 0.9137   ┆ 0.036288 ┆ 0.384691 ┆ 0.033483 │
│ 300409 ┆ 1.777398 ┆ 2.0757  ┆ 0.729  ┆ … ┆ 3.2943   ┆ 0.027804 ┆ 0.670913 ┆ 0.02554  │
└────────┴──────────┴─────────┴────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [ ]:
import polars as pl
from datetime import date

lf = pl.scan_ipc(
    "/mnt/raid0/user_data/data_frames/barra_fd_cache/fdmt_main_data_pit_2019-12-31_2025-12-31.feather"
)
lf = (
    lf.filter()
    .select(["sec_id", "publish_date", "end_date", "da"])
    .filter(
        pl.col("publish_date") <= date(2025, 11, 28),
        pl.col("da").is_not_null(),
        pl.col("da").is_not_nan(),
        pl.col("sec_id").is_not_null(),
    )
    .sort("sec_id", "end_date", "publish_date")
    .unique("sec_id", keep="last")
    .select(["sec_id", "da"])
)
df = lf.collect()
# df.select("sec_id").filter(~pl.col("sec_id").is_null())
# df.filter(pl.col("da").is_not_null())
# df.select("da").count()
df

shape: (5_280, 2)
┌────────┬───────────┐
│ sec_id ┆ da        │
│ ---    ┆ ---       │
│ str    ┆ f64       │
╞════════╪═══════════╡
│ 000002 ┆ 5.3064e9  │
│ 000004 ┆ 7777281.5 │
│ 000005 ┆ 1.0134e7  │
│ 000006 ┆ 3.5364e7  │
│ 000007 ┆ 5.4181e6  │
│ …      ┆ …         │
│ 688805 ┆ 8.1834e6  │
│ 688807 ┆ 1.8197e7  │
│ 688819 ┆ 5.1774e8  │
│ 688981 ┆ 1.2731e10 │
│ 689009 ┆ 1.2347e8  │
└────────┴───────────┘

In [ ]:
import polars as pl

table_name = "mkt_div_yield"
start_date = "20251112"
end_date = "20251114"
MYSQL_URI = "mysql://readonly_user:readonly_user@119.253.67.3:3306/mydb"

query = f"""
SELECT TICKER_SYMBOL, TRADE_DATE, DIV_RATE_L12M
FROM {table_name}
WHERE TRADE_DATE BETWEEN '{start_date}' AND '{end_date}'
"""
ori_df = pl.read_database_uri(query, MYSQL_URI, engine="connectorx")
lf = (
    ori_df.lazy()
    .rename({col: col.lower() for col in ori_df.columns})
    .rename({"ticker_symbol": "sec_id"})
    # .with_columns(
    #     pl.col("trade_date").str.to_date("%Y%m%d"),
    # )
    .sort(["sec_id", "trade_date"])
)
print(lf.collect())

shape: (16_344, 3)
┌────────┬────────────┬───────────────┐
│ sec_id ┆ trade_date ┆ div_rate_l12m │
│ ---    ┆ ---        ┆ ---           │
│ str    ┆ date       ┆ f64           │
╞════════╪════════════╪═══════════════╡
│ 000001 ┆ 2025-11-12 ┆ 5.1199        │
│ 000001 ┆ 2025-11-13 ┆ 5.1111        │
│ 000001 ┆ 2025-11-14 ┆ 5.0894        │
│ 000002 ┆ 2025-11-12 ┆ 0.0           │
│ 000002 ┆ 2025-11-13 ┆ 0.0           │
│ …      ┆ …          ┆ …             │
│ 920985 ┆ 2025-11-13 ┆ 2.58          │
│ 920985 ┆ 2025-11-14 ┆ 2.5329        │
│ 920992 ┆ 2025-11-12 ┆ 0.392         │
│ 920992 ┆ 2025-11-13 ┆ 0.3918        │
│ 920992 ┆ 2025-11-14 ┆ 0.3947        │
└────────┴────────────┴───────────────┘

In [ ]:
import polars as pl
import os
from datetime import date

cache_dir = "/mnt/raid0/user_data/data_frames/barra_fd_cache/"
fin_table = "mkt_div_yield"
trd_days = [
    date.fromisoformat(f"{d[:4]}-{d[4:6]}-{d[6:]}")
    for d in ["20251114", "20251113", "20251112"]
]
trd_days.sort()
rev_trd_days = sorted(trd_days, reverse=True)

cache_file = os.path.join(
    cache_dir, f"{fin_table}_{rev_trd_days[0]}_{rev_trd_days[-1]}.feather"
)

lf = pl.scan_ipc(cache_file)
print(lf.collect())

shape: (0, 3)
┌────────┬────────────┬───────────────┐
│ sec_id ┆ trade_date ┆ div_rate_l12m │
│ ---    ┆ ---        ┆ ---           │
│ str    ┆ date       ┆ f64           │
╞════════╪════════════╪═══════════════╡
└────────┴────────────┴───────────────┘

In [1]:
import polars as pl
import os
from datetime import date

trd_date = date(2025, 10, 24)
lf = pl.scan_ipc("/mnt/raid0/user_data/daily_factors/barra/20251024.feather")
df = lf.collect()
df.count()

FileNotFoundError: No such file or directory (os error 2): /mnt/raid0/user_data/daily_factors/barra/20251024.feather

This error occurred with the following context stack:
	[1] 'ipc scan'
	[2] 'sink'